### ISSUE TITLE
website (tredly.com) down with a 502 Bad Gateway

### ISSUE THREAD

**Issue by jf** [tredly/tredly#114]
sorry for opening a ticket about it here, but... this seemed like the most reliable way to contact you guys. It's been down for a while now.

**Comment by nathanaherne** [comment]
Thank you for telling us about this. We have found the problem (unusual IPFW error) and are trying to fix the issue.

**Comment by laurieodgers** [comment]
Hi @jf thank you again for bringing this to our attention. 

This issue has now been fixed and tredly.com is now up again. The issue was to do with IPFW and tredly's neglect on lack of recycling of rules (net.inet.tcp.fast_finwait2_recycle).

If this issue is encountered by anyone else, please set "net.inet.tcp.fast_finwait2_recycle" with sysctl to a value of your choice.

I will be doing up a ticket to have this addressed in the next release.

**Comment by jf** [comment]
thanks, guys. Appreciate the fast response and explanation!
